### ISSUE TITLE
Data description

### ISSUE THREAD

**Issue by jintangxin** [gridclub/Hack2O#3]
Hi All,
Could anyone help to explain what PropertyinfoDBID, house_letter and Samp_No are?
I can definitely guess what they are but still need more accurate clarification and description of these names.

Thanks

**Comment by emmakearney** [comment]
Hey Tangxin!

Take for example, data point/sample S01bj: 

S01bj - The S refers to "sample", 01 is the sample number, and bj is the house letter. Multiple samples were taken in succession at each unique house/property.

Notice each unique sample group starts with a sample that begins with a "DS" instead of an "S". Also note the time on the DS data point is later than the corresponding S data points. This indicates the sample came from the main distribution line, and not the house. 

The samples were taken with the water continuously running, with someone filling water bottles sequentially and counting them as samples. As Joe mentioned in the presentation, the first few samples will have a high concentration of contaminants due to the water sitting in the house pipes. As time continues, the water drawn will be "fresher". By the end of the sampling time, the water will really represent the quality of the water in the main distribution line, rather than the water quality from sitting in house pipes. Therefore, this "DS" data point will (likely) have low contaminant concentrations. 

I believe the PropertyinfoDBID  is consistent across the two spreadsheets.

**Comment by ghost** [comment]
Hey Emma, just to clarify, do you mean that PropertyinfoDBID is a primary key meaning does the sub_location in the chlorine_and_pH file correspond to the sublocation for the corresponding PropertyinfoDBID in the Copper and Iron data file?

**Comment by ospiro** [comment]
@ajavaid17 Yes, the ID is shared between the two documents. Joe Goodwill has warned about the one possible exception of property 8. See the slides for his commentary on that.

EDIT: Actually, I think the question on sub_location may need to wait for a comment from Joe tomorrow to confirm.

**Comment by heyitsjoe** [comment]
Yes, PropertyInfoDBID is the primary key, and should correspond across data sets.
